### ISSUE TITLE
public or private?

### ISSUE THREAD

**Issue by akira-okumura** [cta-chec/CHECLabPy#17]
CHECLabPy is a public project at the moment. Namely anyone can view it even without a GitHub account. As cta-chec is not a standard free account, we can make the project private from "Settings" tab if necessary.

**Comment by watsonjj** [comment]
Yes, we decided to make this particular project public. I don't see any reason to hide the code we write here. The methods inside are very simple, and if anyone outside of CHEC got hold of some dl1 files (which are pandas dataframe HDF5 files) theres nothing to stop them opening them and doing analysis anyway. By having it public, it could help with coordination and discussion with ASWG members.

**Comment by akira-okumura** [comment]
OK, understand.
