### ISSUE TITLE
Add interactive event viewer script

### ISSUE THREAD

**Issue by watsonjj** [cta-chec/CHECLabPy#18]
The event viewer we had in the past was my most powerful tool for fast debugging. That relied on ctapipe, so I would like to make a similar event viewer for CHECLabPy that takes in a r0/r1/dl1 file, and allows you to interactively look trough events and see waveforms and camera images.

It will use bokeh as the previous viewer did.

**Comment by RichardWhite109** [comment]
I would really not do this in CHECLabPy. The idea of this package is to provide a very simple and easy to understand tool for reducing data, and opening that reduced data. I have a fast waveform plotter that I use on the CS to check if r0 and r1 data is ok. I could add that. I was also going to add the ability to draw on parameters from a dl1 file. I think that whilst an interactive viewer is nice, it should be a separate small package (which could use the CHECLapPy reader). More importantly we should view this as very low priority. All that said, I'm open to trying it - the above is just my opinion, but if it makes this package more complicated, then I would really not do it this way. Also Bokeh was pretty slow in the past - any viewer should allow events to be played back at up to 2-10 Hz... perhaps this is possible?

**Comment by watsonjj** [comment]
Regarding your last point, I'm not proposing a "live" viewer, speed is not a factor in this. This will let you click event by event to see certain values per pixel.

I will create it in CHECLabPy to begin with, you are right that it could exist outside of it. But I don't think it will make the package more complicated, and its a very useful tool that I can see anyone using...

**Comment by watsonjj** [comment]
Also, a point for the future, we never encountered speed issues with bokeh in the past, and can achieve rates much higher than 10 Hz.

**Comment by RichardWhite109** [comment]
I'd just ask that we do not prioritise this. The TFs and charge resolution are (much) more important. The point of this package is to allow others to analyse data - and it's basically finished in that regard. Good that Bokeh is fast enough. I would also ask that if we do it this way then it's designed with some key features, here's what I find useful at the moment in the current tool I have:
- Being able to see r0 and r1 in panels very close to each other with common x-axis
- X-axis formatting in multiples of 8 samples with grid lines, and 0 and eg. 127 included
- I have a few different waveform views:
-- r0
-- r1 Chosen pixel (black), TM mean (grey), ASIC means (4 colours)
-- r1 Persistance / history for chosen pixel: current event (black), last 100 events (some colour with alpha=0.6)
-- r1 all 64 pixels in the TM of the chosen TM, colour coded by ASIC as in the other plot
- Then I draw on the event time, the pulse time, the pulse amp, the baseline and the 'window' defined by tevent for integration / searching 
- In 2D I was going to add the running mean extracted charge, the extracted charge in the current event, and the tpulse
- I also wanted to add some scatter plots vs. event number of:
-- baseline, rms, charge, tpulse (all for 1 pixel and the mean over the camera) and tevent

In general it's very helpful to see the events 'play back' for 1 chosen pixel. I agree that being able to chose a pixel for 1 event and plot different quantities is also helpful... at the moment I just hit ctrl-c and run again for a different pixel. 

What are the use cases for this viewer: presumably the camera operator and developers of waveform_reducers? For the former, I would add the limitation that the new CS will not have a x-server running directly on it. All drawing has to be done via ssh -Y or with the disk mounted over sshf. We could consider running a Bokeh server and connecting in remotely, but really running anything else on the CS will be killed if we find that it effects the raw data collection.

**Comment by watsonjj** [comment]
It did add extra complexity, so I have created a separate github repository where this would be added:
https://github.com/watsonjj/CHECLabPy_eventviewer

**Comment by RichardWhite109** [comment]
I think this is a good decision. Better to keep this library slim. Once it's working well perhaps we should just remove all plotting from this library?

**Comment by watsonjj** [comment]
I think the camera plotter is still useful to keep
