### ISSUE TITLE
Add monitor information by default in extract_dl1?

### ISSUE THREAD

**Issue by RichardWhite109** [cta-chec/CHECLabPy#22]
At the moment we specify a monitor file: python extract_dl1.py -f refdata/Run17473_r1.tio -m refdata/Run17473.mon, but extract_dl1 could just contruct "refdata/Run17473.mon", check it exists, print "mon file found" and add the data automatically

**Comment by watsonjj** [comment]
We could, but perhaps there are times when a user wants to quickly create the dl1 file without the additional processing time required for the monitor data, but they may have the monitor file sat in the same directory.

**Comment by RichardWhite109** [comment]
I think you're right - we can just leave it to cover the following use cases:
1. Run#_r1.tio and Run#.mon in directory and wants monitor data in dl1 
-- Most of the time 
-- User specifies mon file (bit of a pain - eg if we also pull info from a .conf file later)
-- Alternative - make looking for mon file default 
2. Run#_r1.tio and Run#.mon in directory and doesn't wants monitor data in dl1 
-- Rare, but agree should be possible to run via the script
-- Just don't specify anything
-- Alternative: user specifies '--nomon'
3.  Run#_r1.tio and Run#.mon not in directory, or a different name - for example one large monitor file that covers several runs (I guess the script might still work?)
-- Rare
-- User specifies mon file
-- Alternative: don't allow this / user specifies '-m' / '--mon'
