### ISSUE TITLE
Create an empty monitor object if no mon file exisits?

### ISSUE THREAD

**Issue by RichardWhite109** [cta-chec/CHECLabPy#23]
At the moment dl1 reader scripts can fail if a file is given without the monitor data frame include.... one solution is to check that eg. reader.monitor is not None before doing reader.monitor.load_entire_table.... another is to have meta item to indicate if monitor data was added... e.g. if reader.metadata["mon"]... or to just always create the monitor object and add functionality to fail gracefully if an item / column is not found??

**Comment by watsonjj** [comment]
```
In [1]: from CHECLabPy.core.io import DL1Reader

In [2]: r = DL1Reader("/Users/Jason/Software/CHECLabPy/refdata/Run17473_dl1.h5")
Opening HDF5 file: /Users/Jason/Software/CHECLabPy/refdata/Run17473_dl1.h5

In [3]: r.monitor.metadata
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-409c4c95da54> in <module>()
----> 1 r.monitor.metadata

AttributeError: 'DL1Reader' object has no attribute 'monitor'
```
This is how it currently fails. I will instead change it to inform the user that there is no monitor table inside the file, but I would still raise the error, it doesn't make sense to let it fail any more gracefully than that.

**Comment by watsonjj** [comment]
If users want to continue doing some processing in their script even if their attempt at accessing the monitor information failed because there is no monitor information in the file, then they should `try ... except AttributeError ...` to catch that error

**Comment by RichardWhite109** [comment]
As I say - that's ok, but as an arbitrary example if I have a class with a member "X", then I can either just pass the buck if a user calls myclass.X and say they have to deal with that not exisiting, even though they may have no idea why it should / shouldn't exisit. Or I can make GetX() that returns None and prints "Warning X does not exist in the file, setting to None, proceed at your own peril". Then the user calls mycall.GetX() and thinks "ah, ok", but looks like everything else still works, I wonder who forgot to put X there". It's just a choice.
