### ISSUE TITLE
Add additional monitor data / data-frames

### ISSUE THREAD

**Issue by RichardWhite109** [cta-chec/CHECLabPy#24]
Add addtional monitor data to the dl1 file format following the approach:
- 3 data frames, 1 for camera items, 1 for per TM items, 1 for per pix items
- Add at least the following:
-- SB temps, currents, voltages, fan speeds (cam)
-- Chiller temps and status (cam)
-- DACQ temps (cam)
-- BP trigger rate (cam)
-- BP TM Voltages and Currents (tm)
-- TM temps (tm)
-- SiPM V and I (pix)

**Comment by watsonjj** [comment]
I did this didn't I? This can be closed now?

**Comment by watsonjj** [comment]
Functionality added by #48 and #51
