### ISSUE TITLE
Change "AverageWF" to "Default" or similar

### ISSUE THREAD

**Issue by RichardWhite109** [cta-chec/CHECLabPy#49]

**Comment by watsonjj** [comment]
It is the default for now, but perhaps not in the future. AverageWF is more descriptive as to what it does than "default".

In the help message of extract_dl1.py it states which reducer is used by default: 
"WaveformReducer to use (default: AverageWF)"

And this is automatically included in the help message. If we change the default, then the help message automatically updates.

**Comment by RichardWhite109** [comment]
Sorry - didn't mean to create and issue from this backlog card, was just showing someone how the new github project kanban board works
