### ISSUE TITLE
Typo in import of Plotter class in camera.py

### ISSUE THREAD

**Issue by sflis** [cta-chec/CHECLabPy#88]
In `plotting/camera.py` when importing the Plotter class, `CHECLabPy` is miss-typed as `CHECLabPySB` which results in an import error.: 

https://github.com/cta-chec/CHECLabPy/blob/95d1f85c3786d59b3fae0f985d291d7df0532ed4/CHECLabPy/plotting/camera.py#L1

**Comment by watsonjj** [comment]
Fixed in #89. Thanks for reporting!

**Comment by sflis** [comment]
This can be closed
